version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    volumes:
      - ./:/src/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    container_name: db
    image: postgres:latest
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: eng_web_g41
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password